# Generated by Django 5.0.4 on 2024-06-25 01:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
